/* eslint-disable import/prefer-default-export */
/* Populated by react-webpack-redux:action */
export const TOGGLE_GATES = 'TOGGLE_GATES';
export const TOGGLE_DOUBLE_LINE = 'TOGGLE_DOUBLE_LINE';
export const SET_MARKER_SPACING = 'SET_MARKER_SPACING';
export const SET_GATE_SPACING = 'SET_GATE_SPACING';
export const SET_MAP = 'SET_MAP';
export const START_ADDING_POINT = 'START_ADDING_POINT';
export const STOP_ADDING_POINT = 'STOP_ADDING_POINT';
export const CLOSE_TRACK = 'CLOSE_TRACK';
export const OPEN_TRACK = 'OPEN_TRACK';
export const DELETE_POINT = 'DELETE_POINT';
export const TOGGLE_GRID_SNAP = 'TOGGLE_GRID_SNAP';
export const RENDER_PREVIEW = 'RENDER_PREVIEW';
export const SET_TRACK_WIDTH = 'SET_TRACK_WIDTH';
export const SET_TRACK_TEXT = 'SET_TRACK_TEXT';
export const SET_NAME = 'SET_NAME';
export const SET_RACE_TEXT = 'SET_RACE_TEXT';
export const ENABLE_DOWNLOAD = 'ENABLE_DOWNLOAD';
export const SET_MARKER_TYPE = 'SET_MARKER_TYPE';
